import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {alarmSongs,songById,createAlarmPlayer,countdownTrack,parseTune} from '../alarm-music.js';
function harness(){const audio={paused:true,pause(){this.paused=true},load(){},removeAttribute(){this.src=''},play(){this.paused=false;return Promise.resolve()}};return {audio,player:createAlarmPlayer(null,{makeAudio:()=>audio})}}
test('every tune uses a bundled instrument recording and loops until stopped',async()=>{for(const song of alarmSongs){const {audio,player}=harness();await player.play(song.id,.7);assert.equal(player.songId,song.id);assert.equal(audio.src,'assets/audio/'+song.id+'.wav');assert.equal(audio.loop,true);assert.equal(audio.volume,.7);assert.equal(player.playing,true);player.stop();assert.equal(audio.paused,true);assert.equal(player.playing,false);assert.ok(['piano','marimba','cello','guitar','bass'].includes(song.instrument))}});
test('changing tune stops the previous media and unknown choices use piano',async()=>{const {audio,player}=harness();await player.play('calm');await player.play('steps');assert.equal(audio.src,'assets/audio/steps.wav');assert.equal(songById('old').id,'calm');audio.paused=true;assert.equal(player.playing,false)});
test('countdown audio carries quiet music then the alarm without requiring a JS timer',async()=>{const tune={rate:4,samples:Uint8Array.of(140,150,160,170)},blob=countdownTrack(2,tune,tune),pcm=parseTune(await blob.arrayBuffer());assert.equal(pcm.samples.length,(2+600)*4);assert.deepEqual([...pcm.samples.slice(0,4)],[129,130,131,131]);assert.deepEqual([...pcm.samples.slice(8,12)],[140,150,160,170]);assert.equal(pcm.rate,4)});
test('recordings are valid, distinct, conservatively limited, and credited',()=>{const hashes=new Set();for(const song of alarmSongs){const bytes=readFileSync(new URL('../assets/audio/'+song.id+'.wav',import.meta.url));const tune=parseTune(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));assert.equal(tune.rate,11025);assert.ok(tune.samples.length>60000);assert.ok(tune.samples.every(v=>v>=50&&v<=206));hashes.add(bytes.toString('base64'))}assert.equal(hashes.size,alarmSongs.length);assert.match(readFileSync(new URL('../assets/audio/CREDITS.txt',import.meta.url),'utf8'),/Creative Commons Attribution 3.0/)});
