import test from 'node:test';
import assert from 'node:assert/strict';
import {moveCalendarRoom,undoCalendarRoomMove,upcomingCalendarEntries} from '../house-calendar.js';
const due=day=>new Date(2026,9,day).toISOString();
const make=()=>({rooms:[{id:'bath',name:'Bathroom'},{id:'kitchen',name:'Kitchen'}],tasks:[{id:'a',text:'Sink',roomId:'bath',recurrence:{kind:'weeks',every:1},nextDue:due(12),activeSince:due(12),bucket:'now'},{id:'b',text:'Mirror',roomId:'bath',dueDate:due(12),allowanceDays:3},{id:'c',text:'Floor',roomId:'bath',recurrence:{kind:'weekdays',days:[1]},nextDue:due(19)},{id:'d',text:'Hob',roomId:'kitchen',dueDate:due(12)},{id:'child',text:'Tap',parentId:'a',roomId:'bath'},{id:'done',text:'Bath',roomId:'bath',done:true,dueDate:due(12)},{id:'paused',text:'Towels',roomId:'bath',pausedAt:due(1),nextDue:due(12),recurrence:{kind:'days',every:2}}],appointments:[],errands:[]});
const move={ids:['a','b','c','d','child','done','paused'],roomId:'bath',from:'2026-10-12',to:'2026-10-14'};
test('room move changes only unfinished root tasks represented that day, preserves recurrence and undoes exactly',()=>{const state=make(),before=structuredClone(state),undo=moveCalendarRoom(state,move,+new Date(2026,9,10));assert.equal(undo.length,2);assert.deepEqual(state.tasks[0].recurrence,before.tasks[0].recurrence);assert.equal(state.tasks[0].scheduled,true);assert.equal(state.tasks[1].allowanceDays,3);assert.equal(state.tasks[1].scheduled,true);assert.deepEqual(state.tasks.slice(2),before.tasks.slice(2));assert.equal(upcomingCalendarEntries(state).filter(e=>e.roomId==='bath'&&e.date==='2026-10-14').length,2);assert.equal(undoCalendarRoomMove(state,undo),2);assert.deepEqual(state,before)});
test('drop checks current source date, preserving tasks edited during dragging',()=>{const state=make();state.tasks[0].nextDue=due(13);assert.equal(moveCalendarRoom(state,move).length,1);assert.equal(state.tasks[0].nextDue,due(13))});
test('undo keeps later schedule edits and completions',()=>{const state=make(),undo=moveCalendarRoom(state,move);state.tasks[0].nextDue=due(20);state.tasks[1].done=true;assert.equal(undoCalendarRoomMove(state,undo),0);assert.equal(state.tasks[0].nextDue,due(20));assert.equal(state.tasks[1].done,true)});
test('same-day drop and invalid dates change nothing; past dates become active',()=>{const state=make(),before=structuredClone(state);assert.deepEqual(moveCalendarRoom(state,{...move,to:move.from}),[]);assert.throws(()=>moveCalendarRoom(state,{...move,to:'2026-02-30'}));assert.deepEqual(state,before);moveCalendarRoom(state,{...move,to:'2026-10-09'},+new Date(2026,9,10));assert.equal(state.tasks[0].scheduled,false);assert.equal(state.tasks[1].scheduled,false)});
import {renderLocalCalendar} from '../house-calendar.js';
class Element{
 constructor(tag='div'){this.tag=tag;this.children=[];this.className='';this.dataset={};this.attrs={};this.style={setProperty(){}};this.classList={contains:n=>this.className.split(' ').includes(n),add:n=>this.className+=' '+n,remove:n=>this.className=this.className.split(' ').filter(x=>x!==n).join(' '),toggle:(n,on)=>on?this.classList.add(n):this.classList.remove(n)}}
 append(...nodes){for(const n of nodes){n.parent=this;this.children.push(n)}}prepend(...nodes){for(const n of nodes)n.parent=this;this.children.unshift(...nodes)}replaceChildren(...nodes){this.children=[];this.append(...nodes)}setAttribute(k,v){this.attrs[k]=v}querySelector(){return null}querySelectorAll(){return this.children.filter(n=>n.classList.contains('calendar-day'))}scrollIntoView(){}setPointerCapture(id){this.capture=id}contains(n){return n===this||this.children.some(c=>c.contains(n))}closest(selector){if(selector==='.calendar-day'&&this.classList.contains('calendar-day')||selector.includes('calendar-room-symbol')&&this.dataset.taskIds)return this;return this.parent?.closest(selector)||null}
}
function pointerFixture(run){const old={document:globalThis.document,sessionStorage:globalThis.sessionStorage,window:globalThis.window};const elements=Object.fromEntries(['#houseCalendarGrid','#calendarView','#calendarRecurring','#calendarSetDay','#calendarMonthLabel','#calendarAgenda','#unscheduledErrands'].map(k=>[k,new Element()]));elements['#calendarView'].value='month';elements['#calendarRecurring'].checked=elements['#calendarSetDay'].checked=true;let hit;
 globalThis.document={createElement:tag=>new Element(tag),body:new Element(),elementsFromPoint:()=>hit?[hit]:[]};globalThis.sessionStorage={getItem:()=>null,setItem(){},removeItem(){}};globalThis.window={innerHeight:900,scrollBy(){}};
 try{const state=make(),moves=[];renderLocalCalendar(state,new Date(2026,9,12),null,{elements,onMoveRoom:move=>{moves.push(move);moveCalendarRoom(state,move)}});const grid=elements['#houseCalendarGrid'],source=grid.children.find(n=>n.dataset.date==='2026-10-12'),target=grid.children.find(n=>n.dataset.date==='2026-10-14'),chip=source.children.find(n=>n.dataset.roomId==='bath');run({state,moves,grid,chip,target,hit:n=>hit=n})}finally{Object.assign(globalThis,old)}}
test('phone touch drag moves every represented task and suppresses the following tap',()=>pointerFixture(({state,moves,grid,chip,target,hit})=>{grid.onpointerdown({pointerType:'touch',pointerId:1,button:0,target:chip,clientX:20,clientY:100});hit(target);grid.onpointermove({pointerType:'touch',pointerId:1,clientX:150,clientY:200,preventDefault(){}});assert.equal(target.classList.contains('calendar-drop-target'),true);grid.onpointerup({pointerId:1,clientX:150,clientY:200,preventDefault(){}});assert.deepEqual(moves[0],{ids:['a','b'],roomId:'bath',from:'2026-10-12',to:'2026-10-14'});assert.equal(state.tasks.length,7);let stopped=false;grid.onclick({preventDefault(){},stopPropagation(){stopped=true}});assert.equal(stopped,true)}));
test('dropping outside a day and cancelling touch leave tasks intact',()=>pointerFixture(({state,moves,grid,chip,hit})=>{const before=structuredClone(state);grid.onpointerdown({pointerType:'touch',pointerId:2,target:chip,clientX:20,clientY:100});hit(null);grid.onpointermove({pointerType:'touch',pointerId:2,clientX:150,clientY:200,preventDefault(){}});grid.onpointerup({pointerId:2,clientX:150,clientY:200,preventDefault(){}});assert.equal(moves.length,0);assert.deepEqual(state,before);grid.onpointercancel();assert.deepEqual(state,before)}));
