import {scheduleFields,scheduleSnapshot,recurringScheduleTasks,nextDueDate,setNextDue,schedulePlan,unchangedScheduleTasks} from './recurring-schedule.js?v=schedule-20261010-v1';
import {recurringSections,recurringTiming,appendRecurringTiming,setTabLabel,appendTaskGroups} from './task-ui.js?v=schedule-20261010-v1';
import {createSymbolCalendar,scheduledCalendarState,roomSymbol,moveCalendarRoom,undoCalendarRoomMove} from './house-calendar.js?v=release-20261010-v3';
import {initTimer,tickTimer,startFocus} from './focus-timer.js?v=phone-timer-20261010-v1';
export {startFocus};
import {freshTask,nextOccurrence,recurrenceLabel,roomMess,DAY,priorityOrdered} from './v2-state.js?v=release-20261010-v3';
import {taskDeadline} from './task-extras.js?v=overdue-20261010-v1';
import {displayPersonName} from './completion-history.js?v=release-20261010-v3';
const $=s=>document.querySelector(s), el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n}, button=(text,run)=>{const n=el('button',text);n.type='button';n.onclick=run;return n};
const dateKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let roomMoveUndo=[];
export function calendarDragOptions(onMoved){return {onMoveRoom:move=>{roomMoveUndo=moveCalendarRoom(api.get(),move);onMoved?.(move);api.save();featureToast(`Moved ${roomMoveUndo.length} tasks to ${new Date(move.to+'T12:00:00').toLocaleDateString()}. Repeat rules stay the same.`)},...(roomMoveUndo.length?{onUndoRoomMove:()=>{const count=undoCalendarRoomMove(api.get(),roomMoveUndo);roomMoveUndo=[];api.save();featureToast(`Restored ${count} tasks. Tasks changed since the move were kept.`)}}:{})}}
let api,importDraft=[],importUndo=[],scheduleUndo=[],toastTimeout,recurringStatus='needs',manualAnchor=new Date(),manualDay=null,manualRoom='',manualSelected=new Set(),manualMessage='';
export function featureToast(text){const n=$('#featureToast');n.textContent=text;n.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>n.hidden=true,5500)}
export function applyPreferences(state,actor){const pref=state.settings?.find(x=>x.id==='preferences-'+actor.id)||JSON.parse(localStorage.getItem('mc-preferences-'+actor.id)||'{}');document.body.classList.toggle('simple-view',!!pref.simple);document.body.classList.add('dark-mode');document.querySelector('meta[name=theme-color]').content='#1A0430';document.body.dataset.snark=pref.snark||'gentle';$('#simpleSettings').hidden=!pref.simple;$('#simpleView').checked=!!pref.simple;$('#snarkLevel').value=pref.snark||'gentle'}
function savePreferences(){const state=api.get(),id='preferences-'+api.actor().id,pref={id,dark:true,simple:$('#simpleView').checked,snark:$('#snarkLevel').value};state.settings=state.settings.filter(x=>x.id!==id);state.settings.push(pref);localStorage.setItem('mc-'+id,JSON.stringify(pref));api.save()}
export function initFeatures(handlers){api=handlers;$('#simpleSettings').onclick=()=>document.querySelector('nav [data-tab="preferences"]').click();$('#simpleView').onchange=savePreferences;$('#snarkLevel').onchange=savePreferences;
 for(const b of document.querySelectorAll('[data-recurring-add]'))b.onclick=()=>editRecurring(null,!document.querySelector('#roomDetail').classList.contains('hide')?sessionStorage.getItem('mc-open-room'):$('#recurringRoom').value||$('#categoryFilter').value||null);
 document.addEventListener('edit-next-due',e=>editNextDue(e.detail?.id));
 document.addEventListener('add-recurring',e=>editRecurring(null,e.detail?.roomId,e.detail?.inline));
 for(const tab of document.querySelectorAll('[data-recurring-status]'))tab.onclick=()=>{recurringStatus=tab.dataset.recurringStatus;renderRecurring()};
 $('#openManualSchedule').onclick=()=>{manualRoom=$('#recurringRoom').value;manualSelected.clear();manualDay=null;manualMessage='';api.openPage('manualSchedule')};$('#closeManualSchedule').onclick=()=>api.openPage('recurring');
 $('#recurringRoom').onchange=renderRecurring;$('#roomSchedule').onclick=editRoomSchedule;
 $('#spreadTasks').onclick=previewSpread;$('#undoSchedule').onclick=undoSchedule;$('#pauseAll').onclick=()=>pauseTasks(api.get().tasks.filter(t=>!t.done&&t.recurrence&&!t.pausedAt));$('#resumeAll').onclick=()=>resumeTasks(api.get().tasks.filter(t=>!t.done&&t.pausedAt));
 $('#taskUpload').onchange=readUpload;$('#applyImport').onclick=applyImport;$('#undoImport').onclick=undoImport;
 initTimer({actor:api.actor,dialog:showDialog,toast:featureToast});
}
export function renderFeatures(){if(!api)return;renderRecurring();if(!$('#manualSchedule').classList.contains('hide'))renderManualSchedule();tickTimer()}
function showDialog(title){const body=$('#featureDialogBody');body.replaceChildren(el('h2',title));$('#featureDialog').showModal();return body}
function renderRecurring(){
 const root=$('#recurringList'),select=$('#recurringRoom'),state=api.get(),selected=select.value;
 select.replaceChildren(new Option('All rooms',''));
 for(const room of state.rooms.filter(r=>!r.archived))select.append(new Option(roomSymbol(room.id)+' '+room.name,room.id));
 select.value=selected;const filter=select.value;root.replaceChildren();
 const series=new Map();
 for(const t of state.tasks.filter(t=>!t.parentId&&!t.done&&t.recurrence&&(!filter||t.roomId===filter))){
  const key=t.roomId+'|'+(t.recurringGroupId||t.seriesId||t.id);
  if(!series.has(key)||Date.parse(t.nextDue||0)<Date.parse(series.get(key).nextDue||0))series.set(key,t);
 }
 const groups=new Map(recurringSections.map(([key])=>[key,[]]));
 for(const t of series.values()){
  const row=appendRecurringTiming(api.card(t,'task'),t),paused=!!t.pausedAt,tools=row.querySelector('.tools');
  if(paused)row.querySelector('.task-complete').disabled=true;
  tools.prepend(button(paused?'Resume':'Pause',()=>paused?resumeTasks([t]):pauseTasks([t])),button('Edit schedule',()=>editRecurring([t])));
  groups.get(recurringTiming(t).status).push(row);
 }
 for(const [key,name] of recurringSections){const rows=groups.get(key),tab=document.querySelector(`#recurringStatusTabs [data-recurring-status="${key}"]`);setTabLabel(tab,name,rows.length);tab.setAttribute('aria-pressed',String(recurringStatus===key));if(key!==recurringStatus)continue;if(rows.length){const byId=new Map(rows.map(row=>[row.dataset.taskId,row]));appendTaskGroups(root,priorityOrdered([...series.values()].filter(task=>byId.has(task.id))),task=>byId.get(task.id))}else root.append(el('p','No tasks here.'))}

}
function editNextDue(id){
 const task=recurringScheduleTasks(api.get()).find(t=>t.id===id);if(!task)return;
 const plan=schedulePlan([task]),body=showDialog('Change next due date'),form=el('form');form.className='editor';body.append(el('h3',task.text));
 form.innerHTML='<label>Next due date<input name="date" type="date" required></label><p class="form-notice" role="status"></p><div class="dialog-actions"><button type="submit">Save date</button></div>';form.elements.date.value=nextDueDate(task)||dateKey(new Date());form.querySelector('.dialog-actions').append(button('Cancel',()=>$('#featureDialog').close()));body.append(form);
 form.onsubmit=e=>{e.preventDefault();const current=unchangedScheduleTasks(api.get(),plan);if(!current.length){form.querySelector('.form-notice').textContent='This task changed on another device. Close and reopen the editor.';return}changeSchedules(current,t=>setNextDue(t,form.elements.date.value));$('#featureDialog').close();featureToast('Next due date saved. Undo is available in Recurring tasks.')};
}
function editRoomSchedule(){
 const body=showDialog('Schedule tasks by room'),f=el('form');f.className='editor';
 f.innerHTML='<fieldset id="scheduleRooms"><legend>Rooms</legend></fieldset><label>Tasks<select name="frequency"><option value="weekly">Weekly tasks</option><option value="all">All recurring tasks</option></select></label><label>Next due date<input type="date" name="date" required></label><label class="checkbox-label"><input type="checkbox" name="fixed" checked>Keep weekly tasks on this weekday</label><p class="form-notice" role="status"></p><button type="submit">Preview these changes</button>';body.append(f);
 const chosen=$('#recurringRoom').value||$('#categoryFilter').value;
 for(const r of api.get().rooms.filter(r=>!r.archived)){const label=el('label'),c=el('input');label.className='checkbox-label';c.type='checkbox';c.name='rooms';c.value=r.id;c.checked=r.id===chosen;label.append(c,el('span',roomSymbol(r.id)+' '+r.name));f.querySelector('fieldset').append(label)}
 f.elements.date.value=dateKey(new Date());
 f.onsubmit=e=>{e.preventDefault();const selected=[...f.querySelectorAll('[name=rooms]:checked')].map(c=>c.value),weekly=t=>(t.recurrence.kind==='weeks'&&t.recurrence.every===1)||(t.recurrence.kind==='days'&&t.recurrence.every===7)||(t.recurrence.kind==='weekdays'&&t.recurrence.days.length===1)||t.recurrence.kind==='fixed-weekday',tasks=recurringScheduleTasks(api.get()).filter(t=>selected.includes(t.roomId)&&(f.elements.frequency.value==='all'||weekly(t))),day=f.elements.date.value,due=new Date(day+'T00:00:00'),fixed=f.elements.fixed.checked;
  if(!tasks.length){f.querySelector('.form-notice').textContent='Choose rooms with matching recurring tasks.';return}
  const pending=schedulePlan(tasks),preview=el('div');preview.append(el('h3',`${tasks.length} tasks → ${due.toLocaleDateString()}`),el('p','Selected rooms are in colour. Other rooms are faded.'));
  const calendar=el('div'),previewState=scheduledCalendarState(api.get(),tasks.map(t=>({id:t.id,date:due.toISOString()})));
  const draw=date=>calendar.replaceChildren(createSymbolCalendar(previewState,date,null,{storageKey:'mc-room-schedule-preview',showRoomFilter:false,focusRoomIds:selected,onJump:draw}));draw(due);preview.append(calendar);
  const apply=open=>{const current=unchangedScheduleTasks(api.get(),pending);changeSchedules(current,t=>{setNextDue(t,day);if(fixed&&weekly(t))t.recurrence={kind:'weekdays',days:[due.getDay()]}});$('#featureDialog').close();if(open)api.openCalendar(due);featureToast(scheduleResult(current.length,pending.length))};
  const actions=el('div');actions.className='dialog-actions';actions.append(button('Apply these dates',()=>apply(false)),button('Apply and open calendar',()=>apply(true)),button('Back',()=>{$('#featureDialog').close();editRoomSchedule()}));preview.append(actions);f.replaceWith(preview);
 };
}
function scheduleResult(updated,total){return `Updated ${updated} ${updated===1?'task':'tasks'}.${updated<total?` ${total-updated} changed elsewhere and were kept.`:''} Undo is available in Recurring tasks.`}
function renderManualSchedule(){
 const state=api.get(),calendar=$('#manualScheduleCalendar'),choices=$('#manualScheduleChoices');
 const draw=date=>{if(dateKey(date)!==dateKey(manualAnchor)){manualDay=null;manualSelected.clear()}manualAnchor=new Date(date);renderManualSchedule()};
 calendar.replaceChildren(createSymbolCalendar(state,manualAnchor,null,{...calendarDragOptions(move=>{manualDay=move.to;manualAnchor=new Date(move.to+'T12:00:00')}),storageKey:'mc-manual-schedule',showRoomFilter:false,showAgenda:false,selectedDay:manualDay,onJump:draw,onSelectDate:date=>{manualDay=dateKey(date);manualAnchor=new Date(date);manualMessage='';renderManualSchedule()}}));
 choices.replaceChildren();const roomLabel=el('label','Choose tasks by room'),roomSelect=el('select');roomSelect.setAttribute('aria-label','Choose tasks by room');roomSelect.append(new Option('All rooms',''));for(const r of state.rooms.filter(r=>!r.archived))roomSelect.append(new Option(roomSymbol(r.id)+' '+r.name,r.id));roomSelect.value=manualRoom;roomSelect.onchange=()=>{manualRoom=roomSelect.value;manualSelected.clear();manualMessage='';renderManualSchedule()};roomLabel.append(roomSelect);choices.append(roomLabel);
 if(!manualDay){choices.append(el('p','Choose a day on the calendar to move tasks to it.'));return}
 choices.append(el('h3','Move tasks to '+new Date(manualDay+'T12:00:00').toLocaleDateString([],{weekday:'long',day:'numeric',month:'long',year:'numeric'})));
 const tasks=recurringScheduleTasks(state,manualRoom).filter(t=>state.rooms.some(r=>r.id===t.roomId&&!r.archived)).sort((a,b)=>String(a.area).localeCompare(String(b.area))||a.text.localeCompare(b.text)),ids=new Set(tasks.map(t=>t.id));for(const id of manualSelected)if(!ids.has(id))manualSelected.delete(id);
 const form=el('form');form.className='editor';const confirm=el('button'),notice=el('p',manualMessage);confirm.type='submit';notice.setAttribute('role','status');
 const update=()=>{confirm.textContent=`Move ${manualSelected.size} ${manualSelected.size===1?'task':'tasks'} to this day`;confirm.disabled=!manualSelected.size};
 if(!tasks.length)form.append(el('p','No recurring tasks for this room.'));
 for(const t of tasks){const label=el('label'),c=el('input');label.className='checkbox-label manual-schedule-task';c.type='checkbox';c.checked=manualSelected.has(t.id);c.onchange=()=>{c.checked?manualSelected.add(t.id):manualSelected.delete(t.id);update()};const due=nextDueDate(t);label.append(c,el('span',`${t.text} · ${state.rooms.find(r=>r.id===t.roomId)?.name||t.area} · ${due?'Due '+new Date(due+'T12:00:00').toLocaleDateString():'No date'}${t.pausedAt?' · Paused':''}`));form.append(label)}
 update();form.append(confirm,notice);choices.append(form);
 form.onsubmit=e=>{e.preventDefault();const selected=tasks.filter(t=>manualSelected.has(t.id));if(!selected.length)return;const plan=schedulePlan(selected),day=manualDay,body=showDialog('Confirm schedule change');body.append(el('h3',`Move ${plan.length} ${plan.length===1?'task':'tasks'} to ${new Date(day+'T12:00:00').toLocaleDateString()}`));const list=el('ul');for(const t of selected)list.append(el('li',t.text+' · '+t.area));body.append(list,el('p','Repeat rules stay the same. Paused tasks stay paused.'));body.append(button('Confirm move',()=>{const current=unchangedScheduleTasks(api.get(),plan);manualMessage=scheduleResult(current.length,plan.length);manualSelected.clear();changeSchedules(current,t=>setNextDue(t,day));$('#featureDialog').close();renderManualSchedule()}),button('Cancel',()=>$('#featureDialog').close()))};
}
function editRecurring(tasks=null,roomId=null,inline=false){const body=inline?$('#quickRecurringBody'):showDialog(tasks?'Edit recurring task':'Add recurring task'),dialog=inline?$('#quickTask'):$('#featureDialog'),f=el('form');if(inline)body.replaceChildren();f.className='editor';f.innerHTML=`<label>Task<input name="text" required maxlength="180"></label>
<details class="optional-section" id="recRoomChoices"><summary>Choose rooms</summary><div class="optional-fields"><fieldset id="recRooms"><legend>Rooms</legend><label class="checkbox-label"><input type="checkbox" name="allRooms">Check all rooms</label></fieldset></div></details>
<label>Repeat<select name="period"><option value="days">Every X days (resets after completion)</option><option value="weeks">Every X weeks (resets after completion)</option><option value="weekdays">Selected weekdays</option></select></label>
<label id="recInterval">Every<input name="every" type="number" min="1" max="3650" value="1" required></label><fieldset id="recWeekdays"><legend>Repeat on</legend></fieldset>
<label>Next due date<input name="due" type="date" required></label>
<label>Subtasks<textarea name="subtasks" rows="2" placeholder="One subtask per line"></textarea></label>
<details class="optional-section" id="recTaskOptions"><summary>Options</summary><div class="optional-fields">
<label class="checkbox-label"><input name="important" type="checkbox">Needs attention</label>
<label class="checkbox-label"><input name="importantWhenOverdue" type="checkbox">Important when overdue</label><p class="meta">Shows at the top of the home page as soon as it is overdue.</p>
<label class="checkbox-label"><input name="fixedDay" type="checkbox">Repeat on a fixed weekday</label><label>Weekday<select name="fixedWeekday">${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=>`<option value="${i}">${day}</option>`).join('')}</select></label>

<label>Mess impact<select name="impact"><option value="normal">Normal</option><option value="small">Small</option><option value="big">Big</option><option value="none">None</option></select></label><label>Assigned to<select name="assignee"><option value="">Anyone</option></select></label>
</div></details><label class="checkbox-label"><input name="doing" type="checkbox">Add to Doing Now</label><p class="form-notice" role="status"></p><div class="dialog-actions"><button type="submit">Save recurring task</button></div>`;
 const cancel=button('Cancel',()=>dialog.close());if(!tasks){cancel.autofocus=true;cancel.focus({preventScroll:true})}f.querySelector('.dialog-actions').append(cancel);body.append(f);const st=api.get(),first=tasks?.[0],originalPlan=tasks?schedulePlan(tasks):null;f.elements.text.value=first?.text||'';const originalDue=first?nextDueDate(first):'';f.elements.due.value=originalDue||dateKey(new Date());f.elements.important.checked=first?.priority==='high';f.elements.importantWhenOverdue.checked=!!first?.importantWhenOverdue;f.elements.fixedDay.checked=first?.recurrence.kind==='fixed-weekday';f.elements.fixedWeekday.value=String(first?.recurrence.day??6);f.elements.period.value=first?.recurrence.kind==='fixed-weekday'?'weeks':first?.recurrence.kind||'weeks';f.elements.every.value=first?.recurrence.every||1;f.elements.impact.value=first?.messImpact||'normal';for(const p of st.householdPeople)f.elements.assignee.append(new Option(displayPersonName(p),p.id));f.elements.assignee.value=first?.assignedTo||'';
 ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach((name,i)=>{const label=el('label'),c=el('input');c.type='checkbox';c.name='weekday';c.value=i;c.checked=first?.recurrence.days?.includes(i)||false;label.className='checkbox-label';label.append(c,el('span',name));f.querySelector('#recWeekdays').append(label)});
 for(const room of st.rooms.filter(r=>!r.archived)){const label=el('label'),c=el('input');c.type='checkbox';c.name='rooms';c.value=room.id;c.checked=tasks?tasks.some(t=>t.roomId===room.id):room.id===roomId;label.className='checkbox-label';label.append(c,el('span',roomSymbol(room.id)+' '+room.name));f.querySelector('#recRooms').append(label)}
 const roomChoices=f.querySelector('#recRoomChoices'),roomSummary=roomChoices.querySelector('summary');
 const updateRooms=()=>{const checked=[...f.querySelectorAll('[name=rooms]:checked')],names=checked.map(c=>st.rooms.find(room=>room.id===c.value)?.name);roomSummary.textContent=checked.length===1?'Room · '+names[0]:checked.length?`Rooms · ${checked.length} selected`:'Choose rooms';if(!checked.length)roomChoices.open=true};
 for(const c of f.querySelectorAll('[name=rooms]'))c.onchange=updateRooms;
 f.elements.allRooms.onchange=()=>{for(const c of f.querySelectorAll('[name=rooms]'))c.checked=f.elements.allRooms.checked;updateRooms()};updateRooms();
 if(!tasks)cancel.focus({preventScroll:true});f.querySelector('#recTaskOptions').open=!!f.elements.fixedDay.checked;
 const update=()=>{const weekdays=f.elements.period.value==='weekdays',fixed=f.elements.fixedDay.checked;f.querySelector('#recWeekdays').hidden=!weekdays||fixed;f.querySelector('#recInterval').hidden=weekdays||fixed;f.elements.every.disabled=weekdays||fixed;f.elements.fixedWeekday.closest('label').hidden=!fixed};f.elements.period.onchange=update;f.elements.fixedDay.onchange=update;update();
 f.onsubmit=e=>{e.preventDefault();const roomIds=[...f.querySelectorAll('[name=rooms]:checked')].map(x=>x.value),days=[...f.querySelectorAll('[name=weekday]:checked')].map(x=>Number(x.value)),kind=f.elements.period.value,notice=f.querySelector('.form-notice');if(!roomIds.length){roomChoices.open=true;notice.textContent='Choose at least one room.';return}if(!f.elements.fixedDay.checked&&kind==='weekdays'&&!days.length){notice.textContent='Choose at least one weekday.';return}const state=api.get();if(tasks&&unchangedScheduleTasks(state,originalPlan).length!==tasks.length){notice.textContent='This task changed on another device. Close and reopen the editor.';return}
 const recurrence=f.elements.fixedDay.checked?{kind:'fixed-weekday',day:Number(f.elements.fixedWeekday.value)}:kind==='weekdays'?{kind,days}:{kind,every:Number(f.elements.every.value)},groupId=first?.recurringGroupId||crypto.randomUUID(),now=new Date().toISOString();
 for(const selected of roomIds){const room=state.rooms.find(r=>r.id===selected),old=tasks?.find(t=>t.roomId===selected),t=old?state.tasks.find(x=>x.id===old.id):freshTask({text:f.elements.text.value.trim(),roomId:room.id,area:room.name},crypto.randomUUID(),now,state.tasks.length);t.text=f.elements.text.value.trim();t.recurrence=recurrence;t.recurringGroupId=groupId;t.priority=f.elements.important.checked?'high':'mid';t.importantWhenOverdue=f.elements.importantWhenOverdue.checked;t.messImpact=f.elements.impact.value;t.assignedTo=f.elements.assignee.value||null;t.assignedToName=state.householdPeople.find(x=>x.id===t.assignedTo)?.name||null;
 if(!old||!t.nextDue||f.elements.due.value!==originalDue){const due=f.elements.due.value?new Date(f.elements.due.value+'T00:00:00').toISOString():old?nextOccurrence(recurrence,new Date(t.lastDone||now)):kind==='weekdays'?nextOccurrence(recurrence,new Date(Date.now()-DAY)):now;t.nextDue=due;t.activeSince=due;t.scheduled=Date.parse(due)>Date.now();t.bucket='now';t.allowanceDays=null}
 if(f.elements.doing.checked){t.doingNow=true;t.doingNowOrder=Math.max(-1,...state.tasks.map(x=>x.doingNowOrder??-1))+1}if(!old)state.tasks.push(t);for(const text of f.elements.subtasks.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean))state.tasks.push({...freshTask({text,roomId:room.id,area:room.name,assignedTo:t.assignedTo,assignedToName:t.assignedToName},crypto.randomUUID(),now,state.tasks.length),parentId:t.id});}
 if(tasks){const removed=new Set(tasks.filter(t=>!roomIds.includes(t.roomId)).map(t=>t.id));state.tasks=state.tasks.filter(t=>!removed.has(t.id))}dialog.close();api.save();featureToast('Recurring task saved.')};
}
const fields=scheduleSnapshot;
function changeSchedules(tasks,update){scheduleUndo=tasks.map(t=>({id:t.id,before:fields(t)}));tasks.forEach(update);scheduleUndo.forEach(item=>item.after=fields(tasks.find(t=>t.id===item.id)));$('#undoSchedule').disabled=!scheduleUndo.length;$('#undoSchedule').hidden=!scheduleUndo.length;api.save()}
function pauseTasks(tasks){changeSchedules(tasks,t=>{t.pausedAt=new Date().toISOString()});featureToast(`${tasks.length} recurring tasks paused.`)}
function resumeTasks(tasks){changeSchedules(tasks,t=>{const shift=Math.max(0,Date.now()-Date.parse(t.pausedAt));if(!t.nextDue)t.nextDue=t.activeSince||t.created;for(const key of ['nextDue','activeSince'])if(Number.isFinite(Date.parse(t[key])))t[key]=new Date(Date.parse(t[key])+shift).toISOString();delete t.pausedAt;if(t.nextDue){t.scheduled=Date.parse(t.nextDue)>Date.now();t.bucket='now'}});featureToast('Recurring tasks resumed. Their dates moved by the pause duration.')}
function undoSchedule(){let count=0;for(const item of scheduleUndo){const t=api.get().tasks.find(t=>t.id===item.id&&!t.done);if(t&&JSON.stringify(fields(t))===JSON.stringify(item.after)){for(const key of scheduleFields)delete t[key];Object.assign(t,item.before);count++}}scheduleUndo=[];$('#undoSchedule').disabled=true;$('#undoSchedule').hidden=true;api.save();featureToast(`Restored ${count} schedules. Tasks changed since then were kept.`)}
function previewSpread(){const body=showDialog('Spread recurring tasks'),intro=el('p','Daily tasks stay as they are. Other tasks are spread across their repeat interval. This includes overdue tasks; review the proposed dates before applying. Completed history stays unchanged.');body.append(intro);const tasks=api.get().tasks.filter(t=>!t.done&&t.recurrence&&!t.pausedAt),load=new Map(),proposals=[];const today=new Date();today.setHours(0,0,0,0);
 for(const t of tasks){const r=t.recurrence;if(r.kind==='days'&&r.every===1)continue;const interval=r.kind==='weekdays'?7:r.every*(r.kind==='weeks'?7:1);let best=null,bestLoad=Infinity;for(let i=0;i<interval;i++){const d=new Date(today);d.setDate(d.getDate()+i);if(r.kind==='weekdays'&&!r.days.includes(d.getDay()))continue;const key=dateKey(d),n=load.get(key)||0;if(n<bestLoad){best=d;bestLoad=n;if(n===0)break}}if(best){load.set(dateKey(best),bestLoad+1);proposals.push({id:t.id,date:best.toISOString(),before:fields(t)})}}
 if(!proposals.length){body.append(el('p','There are no longer-interval active recurring tasks to spread.'));return}body.append(spreadPreviewCalendar(proposals,tasks));const apply=open=>{const valid=proposals.filter(p=>{const t=api.get().tasks.find(t=>t.id===p.id&&!t.done);return t&&JSON.stringify(fields(t))===JSON.stringify(p.before)});changeSchedules(valid.map(p=>api.get().tasks.find(t=>t.id===p.id)),t=>{const p=valid.find(p=>p.id===t.id);t.nextDue=p.date;t.activeSince=p.date;t.scheduled=Date.parse(p.date)>Date.now();t.bucket='now'});$('#featureDialog').close();if(open)api.openCalendar(new Date(valid[0]?.date||Date.now()));featureToast(`Spread ${valid.length} schedules. Undo is available on Recurring tasks.`)};body.append(button('Apply these dates',()=>apply(false)),button('Apply and open calendar',()=>apply(true)))}
function spreadPreviewCalendar(proposals,tasks){
 const root=el('div');root.className='spread-preview';const state=scheduledCalendarState(api.get(),proposals),anchor=new Date(proposals.map(p=>p.date).sort()[0]);
 const draw=date=>root.replaceChildren(createSymbolCalendar(state,date,null,{storageKey:'mc-spread-calendar',onJump:draw}));draw(anchor);return root;
}
// CSV supports quoted commas, quotes and line breaks; no data is evaluated.
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(quoted)throw Error('An opening quote is missing its closing quote.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function importKey(t){return `${t.roomId}|${t.text.trim().toLowerCase()}`}
async function readUpload(e){importDraft=[];$('#applyImport').disabled=true;$('#importPreview').replaceChildren();try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Please use a CSV smaller than 1 MB.');const rows=csvRows((await file.text()).replace(/^\uFEFF/,'')),headers=rows.shift()?.map(x=>x.trim().toLowerCase());if(!headers?.includes('task')||!headers.includes('room'))throw Error('The file needs Task and Room columns. Start with the template.');if(rows.length>1000)throw Error('Please upload at most 1,000 rows at a time.');const state=api.get(),keys=new Set(state.tasks.filter(t=>!t.done).map(importKey));let duplicates=0;const errors=[];
 rows.forEach((row,index)=>{const v=Object.fromEntries(headers.map((h,i)=>[h,(row[i]||'').trim()])),room=state.rooms.find(r=>!r.archived&&r.name.toLowerCase()===v.room?.toLowerCase());if(!v.task||v.task.length>180||!room){errors.push(`Row ${index+2}: use a task name (up to 180 characters) and an exact room name.`);return}const bool=value=>!value||['yes','no','true','false','1','0'].includes(value.toLowerCase());if(!bool(v.attention)||!bool(v['doing now'])){errors.push(`Row ${index+2}: Attention and Doing Now must be yes or no.`);return}const every=Number(v['repeat every']||0),period=(v['repeat unit']||'days').toLowerCase(),due=v['due date'],assigned=v['assigned to'],person=state.householdPeople.find(p=>p.name.toLowerCase()===assigned?.toLowerCase());if((v['repeat every']&&(!Number.isInteger(every)||every<1||every>3650))||!['days','weeks'].includes(period)||(due&&(!/^\d{4}-\d{2}-\d{2}$/.test(due)||!Number.isFinite(+new Date(due+'T00:00:00'))||dateKey(due+'T00:00:00')!==due))||(assigned&&!person)){errors.push(`Row ${index+2}: check repeat interval, date (YYYY-MM-DD) or household member.`);return}
 const t=freshTask({text:v.task,roomId:room.id,area:room.name,priority:['yes','true','1'].includes(v.attention?.toLowerCase())?'high':'mid',assignedTo:person?.id,assignedToName:person?.name},crypto.randomUUID());if(every){t.recurrence={kind:period,every};t.recurringGroupId=crypto.randomUUID();t.nextDue=due?new Date(due+'T00:00:00').toISOString():new Date().toISOString();t.activeSince=t.nextDue;t.scheduled=Date.parse(t.nextDue)>Date.now();t.bucket='now'}else if(due){t.dueDate=new Date(due+'T00:00:00').toISOString()}t.doingNow=['yes','true','1'].includes(v['doing now']?.toLowerCase());t.notes=v.notes||'';const duplicate=keys.has(importKey(t));if(duplicate)duplicates++;keys.add(importKey(t));importDraft.push({task:t,duplicate,add:!duplicate})});
 if(errors.length){importDraft=[];throw Error(errors.join('\n'))}$('#importNotice').textContent=`${importDraft.length} rows read; ${duplicates} potential duplicates. Choose whether to skip each duplicate. Nothing has been added yet.`;for(const item of importDraft){const row=el('div');row.className='import-preview-row';row.append(el('strong',item.task.text+' · '+item.task.area),el('p',item.task.recurrence?recurrenceLabel(item.task):'One-off task'));if(item.duplicate){const label=el('label'),choice=el('select');choice.append(new Option('Skip duplicate','skip'),new Option('Add another task anyway','add'));choice.onchange=()=>{item.add=choice.value==='add';$('#applyImport').disabled=!importDraft.some(x=>x.add)};label.append(el('span','An active task already matches. '),choice);row.append(label)}$('#importPreview').append(row)}$('#applyImport').disabled=!importDraft.some(x=>x.add);
 }catch(error){$('#importNotice').textContent=error.message}}
function applyImport(){const state=api.get(),keys=new Set(state.tasks.filter(t=>!t.done).map(importKey));let newDuplicates=0;for(const item of importDraft){if(item.add&&!item.duplicate&&keys.has(importKey(item.task))){item.duplicate=true;newDuplicates++}}if(newDuplicates){featureToast('Some tasks now match active tasks. Choose whether to add those duplicates.');const root=$('#importPreview');root.replaceChildren();for(const item of importDraft){const label=el('label'),c=el('input');c.type='checkbox';c.checked=item.add&&!item.duplicate;item.add=c.checked;c.onchange=()=>item.add=c.checked;label.className='checkbox-label';label.append(c,el('span',item.task.text+' · '+item.task.area+(item.duplicate?' — duplicate: tick to add anyway':'')));root.append(label)}return}importUndo=[];for(const item of importDraft.filter(x=>x.add)){const t=item.task;t.order=state.tasks.length;if(t.doingNow)t.doingNowOrder=Math.max(-1,...state.tasks.map(x=>x.doingNowOrder??-1))+1;state.tasks.push(t);importUndo.push(structuredClone(t))}importDraft=[];$('#applyImport').disabled=true;$('#undoImport').disabled=!importUndo.length;api.save();$('#importNotice').textContent=`Added ${importUndo.length} tasks. Existing tasks were kept.`;$('#importPreview').replaceChildren()}
function undoImport(){const state=api.get();let removed=0;state.tasks=state.tasks.filter(t=>{const original=importUndo.find(x=>x.id===t.id);if(original&&!t.done&&JSON.stringify(t)===JSON.stringify(original)){removed++;return false}return true});importUndo=[];$('#undoImport').disabled=true;api.save();$('#importNotice').textContent=`Removed ${removed} imported tasks. Tasks edited or completed since import were kept.`}
export {renderLocalCalendar} from './house-calendar.js?v=release-20261010-v3';
