import {alarmSongs,songById,createAlarmPlayer,prepareAlarm} from './alarm-music.js?v=release-20261010-v3';
const key='mc-focus-timer-v1',positionKey='mc-focus-position-v2';
let api,root,mini,label,clock,ringNote,lastToastId;
const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
const save=t=>localStorage.setItem(key,JSON.stringify(t));
let player,previewPlayer,previewing=false,previewTimeout,previewButton;
const songPreference='mc-alarm-song',volumePreference='mc-alarm-volume';
async function audioReady(){player ||= createAlarmPlayer();previewPlayer ||= createAlarmPlayer();if(navigator.audioSession)try{navigator.audioSession.type='playback'}catch{}}
function ring(timer){if(previewing)return;player ||= createAlarmPlayer();if(player.countingDown&&player.playing)return;const song=songById(timer.song).id;if(!player.playing||player.songId!==song)player.play(song,timer.volume??.65).catch(()=>{ringNote.textContent='Tap the timer to resume its music.'})}
function resumeTimerAudio(){const timer=read();if(!timer||timer.actor!==api.actor().id||previewing)return;audioReady();const seconds=Math.max(0,(timer.end-Date.now())/1000);if(player.playing)return;if(seconds&&timer.background){Promise.all([prepareAlarm(timer.song),prepareAlarm('calm')]).then(()=>{const current=read();if(!current||current.end!==timer.end||current.taskId!==timer.taskId||current.actor!==api.actor().id)return;return player.play(timer.song,timer.volume??.65,{seconds:Math.max(0,(timer.end-Date.now())/1000)})}).catch(()=>{ringNote.textContent='Tap the timer to resume countdown audio.'})}else if(!seconds)ring(timer)}
function silence(){player?.stop()}
function stopPreview(){clearTimeout(previewTimeout);if(previewing){previewing=false;previewPlayer?.stop()}if(previewButton)previewButton.textContent='Listen to tune'}
function stop(){localStorage.removeItem(key);stopPreview();silence();tickTimer()}
function position(){let p;try{p=JSON.parse(localStorage.getItem(positionKey)||'null')}catch{}const width=root.offsetWidth||280,height=root.offsetHeight||170;const x=Math.max(8,Math.min(p?.x??innerWidth-width-14,innerWidth-width-8)),y=Math.max(8,Math.min(p?.y??85,innerHeight-height-90));root.style.left=x+'px';root.style.top=y+'px'}
export function initTimer(handlers){api=handlers;root=document.querySelector('#focusStatus');root.className='focus-overlay';root.setAttribute('aria-label','Task timer');root.innerHTML='<div class="focus-drag" tabindex="0" role="button" aria-label="Move timer. Drag, or use arrow keys.">Move timer <span aria-hidden="true">⠿</span></div><strong class="focus-task"></strong><output class="focus-clock" aria-label="Time remaining"></output><p class="focus-ring-note"></p><div class="focus-buttons"><button type="button" data-minimise aria-label="Minimise timer without stopping it">Minimise</button><button type="button" data-stop>Stop timer</button></div>';
 label=root.querySelector('.focus-task');clock=root.querySelector('.focus-clock');ringNote=root.querySelector('.focus-ring-note');root.querySelector('[data-stop]').onclick=stop;root.querySelector('[data-minimise]').onclick=()=>{const t=read();if(t){t.minimised=true;save(t);tickTimer()}};
 mini=document.createElement('button');mini.id='focusMini';mini.type='button';mini.hidden=true;document.body.append(mini);mini.onclick=()=>{const t=read();if(t){t.minimised=false;save(t);resumeTimerAudio();tickTimer();position()}};
 const handle=root.querySelector('.focus-drag');let drag;
 handle.onpointerdown=e=>{if(e.button!==0)return;const rect=root.getBoundingClientRect();drag={x:e.clientX-rect.left,y:e.clientY-rect.top};handle.setPointerCapture(e.pointerId)};
 handle.onpointermove=e=>{if(!drag)return;localStorage.setItem(positionKey,JSON.stringify({x:e.clientX-drag.x,y:e.clientY-drag.y}));position()};
 handle.onpointerup=handle.onpointercancel=()=>drag=null;handle.onkeydown=e=>{const delta={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(delta){e.preventDefault();const rect=root.getBoundingClientRect();localStorage.setItem(positionKey,JSON.stringify({x:rect.left+delta[0],y:rect.top+delta[1]}));position()}};
 window.addEventListener('resize',position);document.addEventListener('visibilitychange',()=>{tickTimer();if(!document.hidden&&player?.countingDown&&player.playing){const t=read();if(t)player.audio.currentTime=Math.max(0,(Date.now()-player.startedAt)/1000)}});window.addEventListener('pageshow',tickTimer);document.addEventListener('pointerdown',()=>{if(read())resumeTimerAudio();tickTimer()},{capture:true});setInterval(tickTimer,250);tickTimer();
}
export function startFocus(task){const body=api.dialog('Time a task'),f=document.createElement('form');f.className='editor';const title=document.createElement('p');title.textContent=task.text;body.append(title);
 f.innerHTML='<label>Minutes<input name="minutes" type="number" min="1" max="240" value="15" required></label><label>Alarm tune<select name="song"></select></label><label>Volume<input name="volume" type="range" min="10" max="100" step="5"></label><button type="button" data-preview>Listen to tune</button><p data-audio-status role="status"></p><p>The chosen tune keeps playing until you press Stop timer, even when minimised.</p><label class="checkbox-label"><input name="background" type="checkbox" checked>Play quiet piano during countdown for screen-lock audio</label><p class="meta">The countdown uses the clock even while your phone is locked. Quiet piano keeps a single audio track playing through to the alarm. Phone settings or interruptions can still stop web audio. Try a one-minute timer on your phone first.</p><p><a href="assets/audio/CREDITS.txt" target="_blank" rel="noopener">Instrument sample credits</a></p><button type="submit">Start timer</button>';body.append(f);
 for(const song of alarmSongs)f.elements.song.append(new Option(song.name+' — '+song.description,song.id));f.elements.song.value=songById(localStorage.getItem(songPreference)).id;f.elements.volume.value=localStorage.getItem(volumePreference)||'65';previewButton=f.querySelector('[data-preview]');const status=f.querySelector('[data-audio-status]');const start=f.querySelector('[type=submit]');
 let loadVersion=0;const load=()=>{const version=++loadVersion;start.disabled=true;status.textContent='Loading instrument sounds…';Promise.all([prepareAlarm(f.elements.song.value),prepareAlarm('calm')]).then(()=>{if(version!==loadVersion)return;start.disabled=false;status.textContent='Sounds ready.'}).catch(()=>{status.textContent='Could not load the sounds. Choose a tune to try again.'})};load();
 previewButton.onclick=async()=>{if(previewing){stopPreview();return}try{await audioReady();previewing=true;await previewPlayer.play(f.elements.song.value,Number(f.elements.volume.value)/100);previewButton.textContent='Stop preview';status.textContent='Playing an 8-second sample.';previewTimeout=setTimeout(()=>{stopPreview();status.textContent='';tickTimer()},8000)}catch{status.textContent='Sound could not start. Try tapping Listen to tune again.'}};
 f.elements.song.onchange=()=>{stopPreview();localStorage.setItem(songPreference,f.elements.song.value);status.textContent='';load()};f.elements.volume.oninput=()=>{localStorage.setItem(volumePreference,f.elements.volume.value);if(previewing)previewPlayer.audio.volume=Number(f.elements.volume.value)/100};
 const dialog=document.querySelector('#featureDialog');dialog.addEventListener('close',stopPreview,{once:true});
 f.onsubmit=e=>{e.preventDefault();stopPreview();silence();audioReady().catch(()=>{});localStorage.setItem(songPreference,f.elements.song.value);localStorage.setItem(volumePreference,f.elements.volume.value);const startedAt=Date.now(),timer={taskId:task.id,text:task.text,actor:api.actor().id,startedAt,end:startedAt+Number(f.elements.minutes.value)*60000,minimised:false,song:f.elements.song.value,volume:Number(f.elements.volume.value)/100,background:f.elements.background.checked};save(timer);if(timer.background){player ||= createAlarmPlayer();player.play(timer.song,timer.volume,{seconds:Number(f.elements.minutes.value)*60}).catch(()=>{ringNote.textContent='Tap the timer to resume countdown audio.'})}if('mediaSession' in navigator){try{navigator.mediaSession.metadata=new MediaMetadata({title:'Task timer: '+task.text,artist:'Mission Control'});navigator.mediaSession.setActionHandler('stop',stop);navigator.mediaSession.setActionHandler('play',resumeTimerAudio)}catch{}}dialog.close();tickTimer();position()}}
export function tickTimer(){if(!api)return;const t=read();if(!t||t.actor!==api.actor().id){root.hidden=true;mini.hidden=true;if(!previewing)silence();return}const left=Math.max(0,Math.ceil((t.end-Date.now())/1000)),display=`${Math.floor(left/60).toString().padStart(2,'0')}:${(left%60).toString().padStart(2,'0')}`,expired=left===0;label.textContent=t.text;clock.textContent=expired?'Time’s up':display;root.classList.toggle('is-ringing',expired);root.hidden=!!t.minimised;mini.hidden=!t.minimised;mini.textContent=expired?'♫':'◷';mini.classList.toggle('is-ringing',expired);mini.setAttribute('aria-label',expired?`Timer ringing for ${t.text}. Open to stop.`:`${display} remaining for ${t.text}. Restore timer.`);mini.title=expired?'Timer ringing — tap to open':display+' remaining';ringNote.textContent=expired?(player?.playing?'You were doing: '+t.text:'Tap the timer to enable its music.'):(t.background?'Quiet piano plays through to the alarm.':'Drag the top edge to move this timer.');if(expired){ring(t);const id=t.taskId+':'+t.end;if(lastToastId!==id){api.toast('You were doing: '+t.text);lastToastId=id}}if(!root.hidden&&!root.style.left)position()}
