import {taskDeadline} from './task-extras.js';
const voices={
 'room-kitchen':{clean:['The kitchen is clean. I shall take the credit.','Counters clear. My imaginary cooking show can resume.'],messy:['The dishes have formed a coalition. I dislike their demands.','That is not a culinary experiment. That is a pile.'],late:'The chef would like “{task}” off the menu.'},
 'room-living':{clean:['A peaceful room. Even my mushrooms have unclenched.','Nothing to tidy. I am photosynthesising smugly.'],messy:['I wanted a woodland retreat, not a laundry habitat.','The cushions are attempting to return to the wild.'],late:'“{task}” has been waiting long enough to grow roots.'},
 'room-master':{clean:['No footprints. No clutter. My reputation remains intact.','A tidy bedroom. Officially rarer than a Bigfoot sighting.'],messy:['I am elusive. The laundry is considerably less so.','The floordrobe is expanding its territory.'],late:'Even I am easier to find than the time for “{task}”.'},
 'room-penny':{clean:['Immaculate. Naturally, I supervised.','I approve. Please record this unusually generous moment.'],messy:['My royal paws require a clear path.','This kingdom has a suspicious number of things on its floor.'],late:'A royal decree: “{task}” is overdue.'},
 'room-bathroom':{clean:['Sparkling. I can finally admire myself professionally.','Clean enough for a water sprite with standards.'],messy:['The soap is doing its best. A little backup, perhaps?','I command water, not whatever that is.'],late:'“{task}” is overdue. The water sprite is making a splash about it.'},
 'room-entrance':{clean:['All parcels accounted for. The dragon is pleased.','A clear entrance! Visitors may now enter without a quest.'],messy:['These parcels are not treasure. I checked. Twice.','Your entrance has become a packaging museum.'],late:'“{task}” has been waiting longer than a parcel delivery window.'},
 'room-hall':{clean:['All routes clear. My tiny clipboard is delighted.','You may pass. Stylishly, even.'],messy:['This is a hallway, not an obstacle qualification course.','Rerouting around the clutter. Again.'],late:'Route recalculated: please visit “{task}”.'},
 'room-cats':{clean:['Clean territory. The cats will be notified. They will ignore me.','The litter troll has nothing to grumble about. Suspicious.'],messy:['The cats have staff. Apparently that means us.','My nose has submitted a strongly worded memo.'],late:'“{task}” is overdue. Even the cats noticed, and they do nothing.'},
 'room-print':{clean:['Workshop ready. I promise not to print more clutter.','Everything in its place. An engineering miracle.'],messy:['We could print an organiser. Or use the one already here.','The workshop is prototyping a mess. Very successfully.'],late:'“{task}” is still in the queue. No filament required.'},
 'room-craft':{clean:['Supplies organised. I can pretend this was my idea.','I can see the table! Quick, admire it before inspiration strikes.'],messy:['These are supplies, not clutter. Except that bit. And that bit.','I collect possibilities. You appear to collect piles.'],late:'“{task}” has become an unfinished project of its own.'}
};
export function characterLine(state,room,mess,level){if(level==='off')return '';const voice=voices[room.id]||{clean:['A clean room. I am quietly taking a bow.'],messy:['The clutter has become rather confident.'],late:'“{task}” is overdue. It has started getting comfortable.'};const overdue=state.tasks.filter(t=>t.roomId===room.id&&taskDeadline(t)!==null&&taskDeadline(t)<Date.now()).sort((a,b)=>taskDeadline(a)-taskDeadline(b));const index=Math.floor(Date.now()/60000);if(overdue.length){const task=overdue[index%overdue.length];return level==='sharp'?voice.late.replace('{task}',task.text):voice.late.replace('{task}',task.text)+' One small step will do.'}const lines=mess.percent===0||mess.state==='CLEAN'?voice.clean:voice.messy;return lines[index%lines.length]}
