import {periodStart} from './periods.js';
import {taskStats} from './task-stats.js';
import {uniqueWins,completionPeople,displayPersonName} from './completion-history.js';
import {completionTrend} from './completion-trend.js?v=cohesion-20261008-v6';
const el=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node};
const number=n=>Number(n.toFixed(1)).toLocaleString();
const dayKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const localInput=at=>{const d=new Date(at);return `${dayKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
function dataCard(title,count,subtitle,metrics,summary='More figures'){
 const card=el('article'),heading=el('div'),name=el('strong',title),total=el('span',count);card.className='data-summary-card';heading.className='data-card-heading';total.className='data-card-total';heading.append(name,total);card.append(heading);if(subtitle)card.append(el('p',subtitle));
 const options=el('details'),list=el('dl');options.className='data-card-figures';options.append(el('summary',summary));for(const [label,value] of metrics){list.append(el('dt',label),el('dd',String(value)))}options.append(list);card.append(options);return card;
}
function personCards(people){const list=el('div');list.className='data-summary-list';for(const p of people)list.append(dataCard(p.name,`${p.recent} this period`,'',[['All time',p.total],['Assigned open',p.assigned]]));return list}
function taskCards(rows,roomName){const list=el('div');list.className='data-summary-list';for(const row of rows)list.append(dataCard(row.text,`${row.count} completed`,roomName(row),[['Average per week',number(row.perWeek)],['Average overdue',row.averageOverdueDays===null?'Unknown':`${number(row.averageOverdueDays)} days`]],'Frequency & overdue'));return list}
function personBars(people){const root=el('div');root.className='person-bars';const max=Math.max(1,...people.map(p=>p.recent));for(const [i,p] of people.entries()){const row=el('div'),label=el('span',p.name),track=el('div'),value=el('strong',String(p.recent));row.className='person-bar';track.className='bar-track';if(p.recent){const bar=el('span');bar.style.width=p.recent/max*100+'%';bar.style.background=`hsl(${150+i*67} 30% 42%)`;track.append(bar)}row.append(label,track,value);root.append(row)}return root}
function lineGraph(state,unit,roomId,personId,period){const data=completionTrend(state,unit,new Date(),roomId,{period,personId}),root=el('div');root.className='completion-line-chart';const heading=el('div');heading.className='line-chart-legend';for(const [index,row] of data.rows.entries()){const label=el('span',row.name);label.className=index?'andy-line':'kayleigh-line';heading.append(label)}root.append(heading);const max=Math.max(0,...data.rows.flatMap(row=>row.counts));if(!max){root.append(el('p','No completions in this graph period.'));return root}const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 640 245');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Task completions by ${unit}: ${data.rows.map(row=>row.name+' '+row.counts.reduce((sum,count)=>sum+count,0)).join(', ')}`);const add=(tag,attributes,text)=>{const node=document.createElementNS(svg.namespaceURI,tag);for(const [key,value] of Object.entries(attributes))node.setAttribute(key,String(value));if(text!==undefined)node.textContent=text;svg.append(node);return node};for(const fraction of max<2?[0,1]:[0,.5,1]){const y=190-fraction*150;add('line',{x1:40,y1:y,x2:625,y2:y,stroke:'#69849c','stroke-width':1});add('text',{x:4,y:y+5,fill:'#eff5ff','font-size':14},String(Math.round(max*fraction)))}for(const [index,bucket] of data.buckets.entries())if(index===0||index===data.buckets.length-1||index%Math.max(1,Math.ceil(data.buckets.length/6))===0)add('text',{x:40+index*585/Math.max(1,data.buckets.length-1),y:219,fill:'#eff5ff','font-size':12,'text-anchor':'middle'},bucket.label);for(const [index,row] of data.rows.entries()){const points=row.counts.map((count,i)=>[40+i*585/Math.max(1,row.counts.length-1),190-count/max*150]);add('polyline',{points:points.map(point=>point.join(',')).join(' '),fill:'none',stroke:index?'#6de0cc':'#ff9bc3','stroke-width':4,'stroke-linecap':'round','stroke-linejoin':'round'});for(const point of points)add('circle',{cx:point[0],cy:point[1],r:4,fill:index?'#6de0cc':'#ff9bc3'})}root.append(svg);return root}
function editCompletion(state,win,onSave){let dialog=document.querySelector('#editCompletionDialog');if(!dialog){dialog=el('dialog');dialog.id='editCompletionDialog';document.body.append(dialog)}dialog.replaceChildren(el('h2','Edit completion'));const form=el('form');form.className='editor';const personLabel=el('label','Completed by'),person=el('select');person.name='person';person.required=true;person.append(new Option('Choose a person…',''));for(const p of completionPeople(state))person.append(new Option(p.name,p.id));person.value=win.completedBy||'';personLabel.append(person);const dateLabel=el('label','Completed on'),date=el('input');date.type='datetime-local';date.name='date';date.required=true;date.min=localInput(Date.now()-90*86400000);date.max=localInput(Date.now());date.value=localInput(win.at);dateLabel.append(date);const status=el('p');status.setAttribute('role','status');const actions=el('div'),save=el('button','Save completion'),cancel=el('button','Cancel');actions.className='dialog-actions';save.type='submit';cancel.type='button';cancel.onclick=()=>dialog.close();actions.append(save,cancel);form.append(personLabel,dateLabel,status,actions);form.onsubmit=e=>{e.preventDefault();const selected=completionPeople(state).find(p=>p.id===person.value),at=new Date(date.value);if(!selected||!Number.isFinite(+at)||+at<Date.now()-90*86400000||+at>Date.now()){status.textContent='Choose a person and a date within the last 90 days.';return}const current=state.wins.find(w=>w.id===win.id);if(!current){status.textContent='This completion is no longer available.';return}current.completedBy=selected.id;current.completedByName=selected.name;current.at=at.toISOString();const task=[...state.tasks,...state.side].find(t=>t.id===(current.taskId||current.id.replace(/^win-/,'')));if(task?.done)task.completedAt=current.at;dialog.close();onSave?.()};dialog.append(form);dialog.showModal()}
function individualRows(state,roomId,personId,onSave,period){const root=el('details');root.className='completion-rows optional-section';const cutoff=periodStart(period,Date.now(),uniqueWins(state).map(win=>Date.parse(win.at)));const rows=uniqueWins(state).filter(w=>(!roomId||w.roomId===roomId)&&(!personId||w.completedBy===personId)&&(Date.parse(w.at)>=cutoff&&Date.parse(w.at)<=Date.now())).sort((a,b)=>String(b.at).localeCompare(String(a.at)));root.append(el('summary',`Individual completions (${rows.length})`));const list=el('div');list.className='optional-fields';root.append(list);for(const w of rows){const row=el('div'),name=el('strong',w.text),who=state.householdPeople.find(p=>p.id===w.completedBy),when=el('span',`${who?displayPersonName(who):w.completedByName||'Unrecorded'} · ${Number.isFinite(Date.parse(w.at))?new Date(w.at).toLocaleString():'Date unknown'}`),edit=el('button','Edit');row.className='completion-row';edit.type='button';edit.onclick=()=>editCompletion(state,w,onSave);row.append(name,when,edit);list.append(row)}if(!rows.length)list.append(el('p','No individual completions in this view.'));return root}
function completionCalendar(state,roomId,personId,onSave){const root=document.querySelector('#dataCalendar');root.replaceChildren();const period=document.querySelector('#statsPeriod').value,rangeStart=periodStart(period,Date.now(),uniqueWins(state).map(win=>Date.parse(win.at))),wins=uniqueWins(state).filter(w=>Number.isFinite(Date.parse(w.at))&&Date.parse(w.at)>=rangeStart&&Date.parse(w.at)<=Date.now()&&(!roomId||w.roomId===roomId));const currentMonth=sessionStorage.getItem('mc-data-month')||dayKey(new Date()).slice(0,7);let anchor=new Date(currentMonth+'-01T12:00:00');if(!Number.isFinite(+anchor))anchor=new Date();const toolbar=el('div'),previous=el('button','‹'),next=el('button','›'),title=el('strong',anchor.toLocaleDateString([],{month:'long',year:'numeric'}));toolbar.className='data-calendar-toolbar';previous.type=next.type='button';const move=months=>{anchor.setMonth(anchor.getMonth()+months);sessionStorage.setItem('mc-data-month',dayKey(anchor).slice(0,7));sessionStorage.setItem('mc-data-day',dayKey(anchor));renderStats(state,roomId,personId,onSave)};previous.onclick=()=>move(-1);next.onclick=()=>move(1);toolbar.append(previous,title,next);root.append(toolbar);
 const grid=el('div');grid.className='data-calendar-grid';for(const day of ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])grid.append(el('strong',day));const start=new Date(anchor.getFullYear(),anchor.getMonth(),1);start.setDate(start.getDate()-(start.getDay()+6)%7);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(d.getDate()+i);const key=dayKey(d),count=wins.filter(w=>dayKey(new Date(w.at))===key&&(!personId||w.completedBy===personId)).length,cell=el('button');cell.type='button';cell.className='data-calendar-day';cell.classList.toggle('outside-month',d.getMonth()!==anchor.getMonth());cell.classList.toggle('today',key===dayKey(new Date()));cell.classList.toggle('selected',key===(sessionStorage.getItem('mc-data-day')||dayKey(new Date())));cell.append(el('span',String(d.getDate())));if(count)cell.append(el('strong',String(count)));cell.setAttribute('aria-label',`${d.toLocaleDateString()}: ${count} completed`);cell.onclick=()=>{sessionStorage.setItem('mc-data-day',key);renderStats(state,roomId,personId,onSave)};grid.append(cell)}root.append(grid);
 const selectedDay=sessionStorage.getItem('mc-data-day')||dayKey(new Date()),dayRows=wins.filter(w=>dayKey(new Date(w.at))===selectedDay).sort((a,b)=>String(a.at).localeCompare(String(b.at)));root.append(el('h3',new Date(selectedDay+'T12:00:00').toLocaleDateString([],{weekday:'long',day:'numeric',month:'long'})));
 const people=completionPeople(state),counters=el('div');counters.className='data-person-counters';const all=el('button',`Everyone ${dayRows.length}`);all.type='button';all.setAttribute('aria-pressed',String(!personId));all.onclick=()=>{document.querySelector('#statsPerson').value='';document.querySelector('#statsPerson').dispatchEvent(new Event('change'))};counters.append(all);for(const p of people){const count=dayRows.filter(w=>w.completedBy===p.id).length,button=el('button',`${p.name} ${count}`);button.type='button';button.setAttribute('aria-pressed',String(personId===p.id));button.onclick=()=>{document.querySelector('#statsPerson').value=p.id;document.querySelector('#statsPerson').dispatchEvent(new Event('change'))};counters.append(button)}root.append(counters);
 const shown=dayRows.filter(w=>!personId||w.completedBy===personId),groups=new Map();for(const w of shown){const person=people.find(p=>p.id===w.completedBy)?.name||w.completedByName||'Unrecorded';if(!groups.has(person))groups.set(person,[]);groups.get(person).push(w)}for(const [person,rows] of groups){const group=el('section');group.className='data-day-group';group.append(el('h4',person));for(const w of rows){const row=el('div');row.className='completion-row';row.append(el('strong',w.text),el('span',`${new Date(w.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · ${state.rooms.find(r=>r.id===w.roomId)?.name||w.area||'General'}`));const edit=el('button','Edit');edit.type='button';edit.onclick=()=>editCompletion(state,w,onSave);row.append(edit);group.append(row)}root.append(group)}if(!shown.length)root.append(el('p','No tasks completed on this day.'));
}
export function renderStats(state,roomId='',personId='',onSave){
 const period=document.querySelector('#statsPeriod').value,graphSelect=document.querySelector('#trendGranularity'),monthlyHistory=period==='0'&&(state.completionArchive||[]).some(row=>row.count&&(!roomId||row.roomId===roomId)&&(!personId||row.completedBy===personId));
 for(const option of graphSelect.options)option.disabled=monthlyHistory&&option.value!=='month';if(monthlyHistory)graphSelect.value='month';
 const unit=graphSelect.value,data=taskStats(state,{days:period,roomId,personId}),overview=document.querySelector('#winsList'),details=document.querySelector('#dataStats'),person=state.householdPeople.find(item=>item.id===personId);
 overview.replaceChildren();details.replaceChildren();
 const summary=el('div');summary.className='stats-summary';summary.append(el('strong',`${data.periodCount} completed${person?' by '+displayPersonName(person):''}`),el('span',`${data.total} all time · ${number(data.perWeek)} per week`));if(monthlyHistory)summary.append(el('small','Older history uses monthly totals.'));overview.append(summary,el('h3','By person'),personBars(data.people),el('h3','Completions over time'),lineGraph(state,unit,roomId,personId,period));
 document.querySelector('#trendGranularity').onchange=()=>renderStats(state,roomId,personId,onSave);
 const roomName=row=>state.rooms.find(r=>r.id===row.roomId)?.name||row.area||'Unknown room';details.append(el('h3','By person'),personCards(data.people),el('h3','Task totals'));
 if(data.rows.length)details.append(taskCards(data.rows,roomName));else details.append(el('p','No task details in this period.'));
 details.append(individualRows(state,roomId,personId,onSave,period),el('p','Completion details are kept for 90 days. Older monthly totals remain in all-time scores.'));
 if(data.unattributed)details.append(el('p',`${data.unattributed} completions have no recorded person.`));if(data.unknownDates)details.append(el('p',`${data.unknownDates} completions lack a usable date and appear only in all-time totals.`));
 completionCalendar(state,roomId,personId,onSave);
 const selectTab=name=>{sessionStorage.setItem('mc-data-tab',name);for(const panel of document.querySelectorAll('[data-data-panel]'))panel.hidden=panel.dataset.dataPanel!==name;for(const tab of document.querySelectorAll('[data-data-tab]'))tab.setAttribute('aria-pressed',String(tab.dataset.dataTab===name))};selectTab(sessionStorage.getItem('mc-data-tab')||'overview');for(const tab of document.querySelectorAll('[data-data-tab]'))tab.onclick=()=>selectTab(tab.dataset.dataTab);
}
